# Generated by Django 6.0.1 on 2026-01-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('cargo', models.CharField(choices=[('autor', 'Autor'), ('editor', 'Editor'), ('administrador', 'Administrador')], default='autor')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('artcileType', models.CharField(choices=[('noticia', 'Noticia'), ('matéria', 'Materia'), ('resenha', 'Resenha')], default='noticia')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('date', models.DateField()),
                ('edited', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hangar18.users')),
            ],
        ),
    ]
