# Generated by Django 6.0.1 on 2026-01-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artcileType', models.CharField(choices=[('noticia', 'Noticia'), ('matéria', 'Materia'), ('resenha', 'Resenha')], default='noticia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hangar18.user')),
            ],
        ),
    ]
