# Generated by Django 6.0.1 on 2026-01-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Publications',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
