# Generated by Django 6.0.1 on 2026-01-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
