# Generated by Django 6.0.1 on 2026-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0002_rename_publications_publication_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='thumb',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
