# Generated by Django 6.0.1 on 2026-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0003_publication_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
