# Generated by Django 6.0.1 on 2026-01-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0004_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='artcileType',
            new_name='articleType',
        ),
    ]
