# Generated by Django 6.0.1 on 2026-01-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar18', '0005_rename_artciletype_publication_articletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
